---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lasample
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: lasample
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 8082
      nodePort: 30080
      name: http
  selector:
    app: nginx
